// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/photo-layout/LeftLarge.tsx": () => import("../components/mockups/photo-layout/LeftLarge.tsx"),
  "./components/mockups/photo-layout/LeftSmall.tsx": () => import("../components/mockups/photo-layout/LeftSmall.tsx"),
  "./components/mockups/photo-layout/RightLarge.tsx": () => import("../components/mockups/photo-layout/RightLarge.tsx"),
  "./components/mockups/photo-layout/RightSmall.tsx": () => import("../components/mockups/photo-layout/RightSmall.tsx")
};
